trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: stage1
    jobs:
      - job: QAJob
        steps:
          - script: echo "Running stage1"

  - stage: stage2
    dependsOn: stage1
    jobs:
      - job: ProdJob
        steps:
          - script: echo "Running stage2"
  
  - stage: stage3
    dependsOn: stage1
    jobs:
      - job: ProdJob
        steps:
          - script: echo "Running stage3"

  - stage: stage4
    dependsOn: 
    - stage2
    - stage3
    jobs:
      - job: ProdJob
        steps:
          - script: echo "Running stage4"
  # - stage: Test
  #   dependsOn: QA
  #   jobs:
  #     - job: Test
  #       steps:
  #         - script: echo Test stage




# Multistage congif with different pool images at stage and job level 
# stages:
#   - stage: A
#     displayName: This is stage A
#     pool:
#       vmImage: ubuntu-latest
#     jobs:
#       - job: Stage_A_job1
#       - job: JobWithJobSpecificPool
#         displayName: Job B running on windows machine
#         pool:
#           vmImage: windows-latest
#         steps:
#           - script: |
#               echo "Stage A Job 1"
#               echo "This is Job 1 from stage A and step 2 using script"
 

 