trigger:
- main

pool: 
  vmImage: ubuntu-latest


stages:
  - stage: A
    displayName: This is stage A
    jobs:
      - job: Stage_A_job1
        steps:
          - script: echo "Stage A Job 1"
          - script: echo "This is Job 1 from stage A and step 2 using script"

          - script: |
              echo "Stage A Job 1"
              echo "This is Job 1 from stage A and step 2 using script"
  - stage: B
    displayName: This is stage B
    jobs:
      - job: 
        steps:
          - bash: echo Hi from Stage B