trigger:
- main

pool: 
  vmImage: ubuntu-latest


stages:
  - stage: A
    jobs:
      - job: Stage_A_job1
        steps:
          - script: echo "Stage A Job 1"
          - script: echo "This is Job 1 from stage A and step 2 using script"