trigger:
- main


stages:
  - stage: A
    displayName: This is stage A
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: Stage_A_job1
      - job: JobWithJobSpecificPool
        displayName: Job B running on windows machine
        pool:
          vmImage: windows-latest
        steps:
          - script: |
              echo "Stage A Job 1"
              echo "This is Job 1 from stage A and step 2 using script"
 