  trigger:
  - none

  parameters:
    - name: Image
      displayName: PoolImage
      default: windows-latest
      type: string
      values:
        - windows-latest
        - ubuntu-latest
        - macOS-latest

      
  jobs:
  - job: RunOnSelectedOS
    displayName: 'Run on selected OS image'
    pool:
      vmImage: ${{ parameters.Image }}

    steps:
      - script: echo "Running on $AGENT_OS"
        displayName: 'Show OS'
    



#  This below code executes condition wether to execute or not based on previous stage. Can also be applied at job level.
# pool:
#   vmImage: ubuntu-latest

# stages:
#   - stage: A
#     jobs:
#       - job: A
#         steps:
#           - script: echo stageA wored

#   - stage: B
#     condition: succeeded('A')
#     jobs:
#       - job: B
        


# Below is example of stage 2 and Stage 3 running parallel and both dependent on stage 1, finally stage 4 dependent on stage 2 and stage 3
# stages:
#   - stage: stage1
#     jobs:
#       - job: QAJob
#         steps:
#           - script: echo "Running stage1"

#   - stage: stage2
#     dependsOn: stage1
#     jobs:
#       - job: ProdJob
#         steps:
#           - script: echo "Running stage2"
  
#   - stage: stage3
#     dependsOn: stage1
#     jobs:
#       - job: ProdJob
#         steps:
#           - script: echo "Running stage3"

#   - stage: stage4
#     dependsOn: 
#     - stage2
#     - stage3
#     jobs:
#       - job: ProdJob
#         steps:
#           - script: echo "Running stage4"


# -------------------------------------------------
  # - stage: Test
  #   dependsOn: QA
  #   jobs:
  #     - job: Test
  #       steps:
  #         - script: echo Test stage




# Multistage congif with different pool images at stage and job level 
# stages:
#   - stage: A
#     displayName: This is stage A
#     pool:
#       vmImage: ubuntu-latest
#     jobs:
#       - job: Stage_A_job1
#       - job: JobWithJobSpecificPool
#         displayName: Job B running on windows machine
#         pool:
#           vmImage: windows-latest
#         steps:
#           - script: |
#               echo "Stage A Job 1"
#               echo "This is Job 1 from stage A and step 2 using script"
 

 