trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: QA
    jobs:
      - job: QAJob
        steps:
          - script: echo "Running Job A from Stage QA"

  - stage: Prod
    # dependsOn: QA
    jobs:
      - job: ProdJob
        steps:
          - script: echo "Running ProdJob After Stage QA"
  - stage: Test
    jobs:
      - job: Test
        steps:
          - script: echo Test stage




# stages:
#   - stage: A
#     displayName: This is stage A
#     pool:
#       vmImage: ubuntu-latest
#     jobs:
#       - job: Stage_A_job1
#       - job: JobWithJobSpecificPool
#         displayName: Job B running on windows machine
#         pool:
#           vmImage: windows-latest
#         steps:
#           - script: |
#               echo "Stage A Job 1"
#               echo "This is Job 1 from stage A and step 2 using script"
 

 